export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="cypher"
zstyle ':omz:update' mode reminder  # just remind me to update when it's time
DISABLE_AUTO_TITLE="true"
plugins=(zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
